### ISSUE TITLE
Select Unifi Controller must be set to DreamMAchine if you use an UniFi-CloudKey-Gen2-Plu 

### ISSUE THREAD

**Issue by lacha07** [Wizzard72/Domoticz-Unifi-Presence#14]
When you want setup the plugin you must choose 
DreamMAchine is you are using an UniFi-CloudKey-Gen2-Plus

**Comment by Wizzard72** [comment]
Thanks. Changed the Plugin hardware setting page with your information. Added ' CloudKey-Gen2'  to Dreammachine.

**Comment by lacha07** [comment]
Merci
