### ISSUE TITLE
Support for Dreammachine

### ISSUE THREAD

**Issue by 111wolf111** [Wizzard72/Domoticz-Unifi-Presence#22]
hi I'm trying to get the plugin to work on my network. I have the dream machine ( not pro ) and I get 
"detect Unifi Devices: Unifi device (UDM) is not present in the table."

I assume this is cause the dreammachine (normal, not pro) is not supported.
Am I right in assuming this?
if so is it possible to add support for it?

Thanks in advance

**Comment by Wizzard72** [comment]
Added the UDM to be detected. Update the plugin

**Comment by 111wolf111** [comment]
Thanks so much, your a champ 👍... working now
Thanks again.
