### ISSUE TITLE
Plugins crash/stop when enabling this plugin

### ISSUE THREAD

**Issue by mcmikev** [Wizzard72/Domoticz-Unifi-Presence#24]
Hi Wizzard72,

Not sure if you are still on the forum, seems rather quiet there so i post it here as well.

I have an issue with this plugin. When I enable the plugin the plugin start fine and there is connection with the UDM-pro
But after a few minutes the crash starts of all of my python plugins.
If i disable this plugin then all works fine and keeps running.
This happens every time I start the plugin.

I have removed all, did fresh pull and same result.
Hope you can find this out because I love this plugin for presence detection on the wifi for automation!

[code]
 2021-10-23 12:10:55.816 Error: Gangkast UPS hardware (34) thread seems to have ended unexpectedly
2021-10-23 12:10:55.817 Error: Zigate hardware (48) thread seems to have ended unexpectedly
2021-10-23 12:10:55.817 Error: Slaapkamer4 CV hardware (49) thread seems to have ended unexpectedly
2021-10-23 12:10:55.817 Error: Gang CV hardware (50) thread seems to have ended unexpectedly
2021-10-23 12:10:55.817 Error: Badkamer CV hardware (51) thread seems to have ended unexpectedly
2021-10-23 12:10:55.817 Error: WK CV hardware (52) thread seems to have ended unexpectedly
2021-10-23 12:10:55.817 Error: Jennifer CV hardware (53) thread seems to have ended unexpectedly
2021-10-23 12:10:55.817 Error: Josslyn CV hardware (54) thread seems to have ended unexpectedly
2021-10-23 12:10:55.818 Error: Slaapkamer1 CV hardware (55) thread seems to have ended unexpectedly
2021-10-23 12:10:55.818 Error: Unifi hardware (69) thread seems to have ended unexpectedly 
[/code]

**Comment by Wizzard72** [comment]
Hi mcmikev,

I'm not on the domoticz forum. Only here.

Sad to hear that your domoticz crashes a lot after enabling my plugin.

I don't know how to troubleshoot that. I have domoticz running also with a lot of plugins and no crashed at all.

What I'm thinking of is that the plugin writes a file to the filesystem. I don't know if you are running domoticz on a raspberry pi with a SD card. But maybe there is something wrong with the filesystem or SD card.

I can't think of another idea why the plugin crashes.

Maybe you can post some more logs so we can invest at what point it crashes.

How long did you run with this plugin before the trouble started? I think at least a few months. So what is changed? Are you on a beta? Or stable? I'm on a stable version.

**Comment by Wizzard72** [comment]
Do you have Python 3.9.x running on your machine? I read that Python couses some errors.

**Comment by mcmikev** [comment]
Hi, sorry for the late response. Busy with work.

No i still run the "old" version of raspbian and even tried with old beta docker image, but the issue is the same.
The plugin will start, run a few times and then crashed and all other python plugins as well.
When I disable the plugin (and only this plugin) all other plugins keep running (Zigate, SVT, UPS)

**Comment by Wizzard72** [comment]
On which version of domoticz are you currently running?

**Comment by mcmikev** [comment]
Running up to date build from source beta tag. 
Problem is with plug-in and udm pro. Running back on CloudKey now and then the crash never happens. So seems like a response of the udm that crashes the plug-in

**Comment by deexiz** [comment]
Hi,
Same problem for me.
Domoticz beta up to date with UDM Pro.

**Comment by Wizzard72** [comment]
When is crashes it means that the plugin somehow timed out. I'm having the same issues with my new rebuild production system based on docker containers. So domoticz runs in a docker. Using the docker the plugin is very very slow, but on my test VM it's very fast and no crashed whatsoever.

**Comment by Wizzard72** [comment]
Can you try the new version?

**Comment by deexiz** [comment]
It seems to be ok.
I'll keep you posted if it crashes again.
Thx for the work.

**Comment by mcmikev** [comment]
Problem is gone for me since the update. Thank you!!!!
