### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by TomMalfrere** [Wizzard72/Domoticz-Unifi-Presence#30]
Hi,
I'm getting the following error:
 2022-01-13 16:06:39.088 Error: Unifi Controller: (Unifi Controller) 'onHeartbeat' failed 'KeyError'.
2022-01-13 16:06:39.088 Error: Unifi Controller: (Unifi Controller) ----> Line 1073 in '/home/pi/domoticz/plugins/Domoticz-Unifi-Presence/plugin.py', function onHeartbeat
2022-01-13 16:06:39.088 Error: Unifi Controller: (Unifi Controller) ----> Line 464 in '/home/pi/domoticz/plugins/Domoticz-Unifi-Presence/plugin.py', function onHeartbeat

could you help me out here?

**Comment by TomMalfrere** [comment]
I'm on the latest Release version 2021.1
I don't see any "Off Delay" switch...

**Comment by Wizzard72** [comment]
Are you on the latest version of the plugin? Please update and share the logs if the problem still exists.

**Comment by sanderdewit** [comment]
check the port number. Dream machine requires port 443

**Comment by Wizzard72** [comment]
Can you make a screenshot of the plugin settings. But first update the plugin with 'git pull' and disable and enable the plugin.

**Comment by sanderdewit** [comment]
I don't have the issue, just noticed when setting it up I saw the same error, this was because I didn't change the port from 8443 to 443.
After that it was working as expected.

**Comment by TomMalfrere** [comment]
I'm running  a unifi controller on a Raspberry Pi on port 8443.
This is how I connect: https://192.168.3.11:8443/manage/site/default/dashboard

**Comment by Wizzard72** [comment]
Can you make a screenshot of the plugin settings. But first update the plugin with 'git pull' and disable and enable the plugin

**Comment by TomMalfrere** [comment]
Ok, I found the problem. I had 18443 for the port number instead of 8443. 18443 is the domoticz port number.
Thanks for asking me to make screenshot. That did the trick!

**Comment by TomMalfrere** [comment]
I still have a problem: the phones that I would like to track remain OFF. They are listed in my Unifi controller.
![image](https://user-images.githubusercontent.com/35227756/150153692-551d06e9-d982-41ae-b23b-d4cc41bda81d.png)
![image](https://user-images.githubusercontent.com/35227756/150153921-b364e433-00bb-49ac-b702-117cc0d9bfff.png)

**Comment by TomMalfrere** [comment]
small question: Why is the port column not filled in for you plugin?
![image](https://user-images.githubusercontent.com/35227756/150159751-4310473d-f5d8-4b9f-8ce3-d1f848c438b6.png)

**Comment by TomMalfrere** [comment]
I have set the site name to default and now it's working...
