### ISSUE TITLE
Application isn't working anymore since 2FA is obligated

### ISSUE THREAD

**Issue by Xavier82** [Wizzard72/Domoticz-Unifi-Presence#41]
Since the obligation to use 2FA (2 factor Authentication) the Domoticz application for Unifi isn't working anymore.

Is it possible to integrate Unifi 2FA in the application?

**Comment by lacha07** [comment]
Hello , you can use a local account instead of your cloud one. On my side it s ok like that

**Comment by Xavier82** [comment]
Thanks, a few weeks ago I found out that a local account indeed works.

**Comment by lacha07** [comment]
@Xavier82 look like you are maintainer now can you take care of my PR? or do I have to do it in your repo?

**Comment by Xavier82** [comment]
ohww? strange, I'm really sorry about this. I was in the assumption that I only posted a question. I'm not maintaining anything, nor can I find a repo on my github.... What can I do to stop this?
